export default [
  {
    key: `1`,
    state: `default`,
    category: `Сказочное заморское яство`,
    title: `Нямушка`,
    filling: `с фуа-гра`,
    info: [`<b>10</b> порций`, `мышь в подарок`],
    weight: 0.5,
    bottomtext: `Печень утки разварная с артишоками.`,
    bottomfailtext: `Печалька, с фуа-гра закончился.`,
  },
  {
    key: `2`,
    state: `selected`,
    category: `Сказочное заморское яство`,
    title: `Нямушка`,
    filling: `с рыбой`,
    info: [`<b>40</b> порций`, `<b>2</b> мыши в подарок`],
    weight: 2,
    bottomtext: `Головы щучьи с чесноком да свежайшая сёмгушка.`,
    bottomfailtext: `Печалька, с рыбой закончился.`,
  },
  {
    key: `3`,
    state: `disabled`,
    category: `Сказочное заморское яство`,
    title: `Нямушка`,
    filling: `с курой`,
    info: [`<b>100</b> порций`, `<b>5</b> мышей в подарок`, `заказчик доволен`],
    weight: 5,
    bottomtext: `Филе из цыплят с трюфелями в бульоне.`,
    bottomfailtext: `Печалька, с курой закончился.`,
  },
]
